### ISSUE TITLE
"socket.cork is not a function" error on node v4.2.1

### ISSUE THREAD

**Issue by nhatquang238** [mattcg/socks5-http-client#12]
So this is the error i get when trying to run the tor example with node v4.2.1:

```
_http_outgoing.js:642
      socket.cork();
             ^

TypeError: socket.cork is not a function
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:642:14)
    at _http_client.js:148:10
    at Socks5ClientSocket.callSocketMethod (_http_client.js:513:7)
    at Socks5ClientSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socks5ClientSocket.emit (events.js:166:7)
    at Socks5ClientSocket.handleSocksConnectToHost (/Users/cocoon/project/coding/bgg/node_modules/socks5-client/lib/Socket.js:133:7)
    at TLSSocket.<anonymous> (/Users/cocoon/project/coding/bgg/node_modules/socks5-https-client/lib/Agent.js:32:29)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.<anonymous> (_tls_wrap.js:1021:14)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
```

**Comment by nhatquang238** [comment]
Sorry wrong repo, this is supposed to be the https one. Closed issue
