### ISSUE TITLE
Error while making more than 5 subsequent request to socks server

### ISSUE THREAD

**Issue by byteshiva** [mattcg/socks5-http-client#18]
I'm getting the following error while making more than 5 subsequent request to locally run socks server on port 1080.

```
 Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socks5ClientSocket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:86:13)
    at Socks5ClientSocket.emit (events.js:185:7)
    at Socket.<anonymous> (/home/xyz/exp/socksv5-client/node_modules/socks5-client/lib/Socket.js:129:8)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

**Comment by mattcg** [comment]
Thanks for filing this. Are you running the requests in parallel or serial? What version of node are you running? Would it be possible to see the some of your code?

**Comment by glazkoman** [comment]
Same issue, here. If doing more than 10 simultaneous connections they are not getting through.
Using it with request-promise library 

Node v7.4.0
